name: "Danger JS"

on: [pull_request]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install yarn
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      - name: Danger
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
